# Generated by Django 4.2.29 on 2026-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Crucial for SEO. Describe the image for search engines.', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Caption displayed below the image.', max_length=250),
        ),
    ]
