# Generated by Django 4.2.29 on 2026-05-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_alt_text_blogpost_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, help_text='Reading time in minutes.'),
        ),
    ]
