# Generated by Django 4.2.29 on 2026-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_reading_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='primary_keyword',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='target_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (e.g. SEO, AI, Growth)', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Use HTML tags for styling: <h2> for subheadings, <ul><li> for points, <strong> for bold.'),
        ),
    ]
